#!/bin/bash
# Daily Scheduler Script
# Runs Claude daily at 8AM to generate daily summary from /Done files

# Set the project root directory to the script's parent directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

# Function to generate daily summary
generate_daily_summary() {
    echo "Generating daily summary..."

    # Get today's date in YYYY-MM-DD format
    TODAY_DATE=$(date +%Y-%m-%d)
    SUMMARY_FILE_NAME="daily_summary_$TODAY_DATE.md"
    SUMMARY_FILE_PATH="Logs/$SUMMARY_FILE_NAME"

    # Create Logs directory if it doesn't exist
    mkdir -p Logs

    # Get all files from the Done directory
    DONE_FILES=""
    if [ -d "Done" ]; then
        DONE_FILES=$(ls -1t Done/ 2>/dev/null | sed 's/^/- /' | tr '\n' '\n' 2>/dev/null)
    fi

    # Create the summary content
    {
        echo "# Daily Summary - $TODAY_DATE"
        echo ""
        echo "## Files Processed Today"
        echo ""
        if [ -n "$DONE_FILES" ]; then
            echo "$DONE_FILES"
        else
            echo "- No files processed today"
        fi
        echo ""
        echo "---"
        echo "Generated by Daily Scheduler at $(date '+%Y-%m-%d %H:%M:%S')"
    } > "$SUMMARY_FILE_PATH"

    echo "Daily summary generated: $SUMMARY_FILE_PATH"
}

# Main execution
generate_daily_summary