# PowerShell Daily Scheduler Script
# Runs Claude daily at 8AM to generate daily summary from /Done files

param(
    [string]$ProjectRoot = $(Get-Location)
)

# Set the project root directory
Set-Location $ProjectRoot

# Function to generate daily summary
function Generate-DailySummary {
    Write-Host "Generating daily summary..." -ForegroundColor Green
    
    # Get today's date in YYYY-MM-DD format
    $todayDate = Get-Date -Format "yyyy-MM-dd"
    $summaryFileName = "daily_summary_$todayDate.md"
    $summaryFilePath = Join-Path "Logs" $summaryFileName
    
    # Create Logs directory if it doesn't exist
    if (!(Test-Path "Logs")) {
        New-Item -ItemType Directory -Path "Logs" -Force
    }
    
    # Get all files from the Done directory
    $doneFiles = @()
    if (Test-Path "Done") {
        $doneFiles = Get-ChildItem -Path "Done" -File | Sort-Object LastWriteTime -Descending
    }
    
    # Create the summary content
    $summaryContent = @"
# Daily Summary - $todayDate

## Files Processed Today

"@ + ($doneFiles | ForEach-Object { "- $($_.Name)" } | Out-String)

    # Add timestamp
    $summaryContent += "`n---`nGenerated by Daily Scheduler at $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`n"
    
    # Write the summary to the file
    $summaryContent | Out-File -FilePath $summaryFilePath -Encoding UTF8
    
    Write-Host "Daily summary generated: $summaryFilePath" -ForegroundColor Green
}

# Main execution
try {
    Generate-DailySummary
} catch {
    Write-Error "Error in daily scheduler: $_"
    exit 1
}